export const defaultSite = {
  companyName: 'Going Studio',
  tagline: 'Creative. Strategy. Performance.',
  description:
    'A digital solutions company combining creative thinking, strategy and performance.',
  email: 'hello@goingstudio.co',
  phone: '+66 98 765 4321',
  location: 'Bangkok, Thailand',
  website: 'https://goingdigital.co.th/',
  experience: '15+ Years of Experience',
  heroEyebrow: 'A Digital Solutions Company',
  heroTitleBefore: 'Where',
  heroTitleAccent: 'Creative Thinking',
  heroTitleAfter: 'Meets Digital Performance',
  heroDescription:
    'Integrated digital experiences for public and private organizations—from websites and brand design to marketing and CRM platforms.',
  aboutTitle: 'Creative. Strategy. Performance.',
  aboutHeading: 'Digital solutions that bring business goals to life',
  aboutBody:
    'Going Digital Solutions delivers digital experiences for public and private organizations. Our experience in graphic design, website design and development is strengthened by a network of specialist partners.',
  contactHeading: "Let's Work Together",
  contactDescription:
    'Tell us about your business goal. We can help shape the right mix of website, design, marketing and CRM capabilities.',
}

export const defaultServices = [
  {
    title: 'Website Development',
    slug: 'website-development',
    summary:
      'Strategic website design and development with thoughtful communication, strong information architecture, refined design and business-fit functionality.',
    detail:
      'Corporate and brand websites, e-commerce websites and campaign websites designed around the needs of each business.',
    order: 1,
  },
  {
    title: 'Graphic Design & Corporate Identity',
    slug: 'graphic-design-corporate-identity',
    summary:
      'Visual communication that strengthens brands, products and organizations through a distinctive and consistent identity.',
    detail:
      'Logos, identity systems, banners, packaging, brochures, menus, catalogs and other creative design applications.',
    order: 2,
  },
  {
    title: 'Digital Marketing',
    slug: 'digital-marketing',
    summary:
      'Objective-led digital marketing plans for launches, brand awareness and sales growth.',
    detail:
      'Campaign planning across Google, Facebook, social media and other channels that fit the business and target audience.',
    order: 3,
  },
  {
    title: 'CRM Platform',
    slug: 'crm-platform',
    summary:
      'Customer engagement platforms for loyalty, acquisition, retention and promotions.',
    detail:
      'Lucky draws, rewards redemption, discounts, surveys, sharing activities and other tailored campaign mechanics.',
    order: 4,
  },
]

export const defaultProjects = [
  {
    title: 'ITALTHAI Group',
    slug: 'italthai-group',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-italthai-07.jpg',
    externalURL: 'https://italthaigroup.com/',
    featured: true,
    order: 1,
  },
  {
    title: 'Dream World',
    slug: 'dream-world',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-dreamworld-08.jpg',
    externalURL: 'https://www.dreamworld.co.th/',
    featured: true,
    order: 2,
  },
  {
    title: 'Faculty of Humanities, Kasetsart University',
    slug: 'kasetsart-humanities',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-kasetsart-humanities-09.jpg',
    externalURL: 'https://human.ku.ac.th/',
    featured: true,
    order: 3,
  },
  {
    title: 'Siambond & Siambond X-Series',
    slug: 'siambond-x-series',
    category: 'website',
    description: 'Website design and development for Siambond and Siambond X-Series',
    image: '/assets/work-siambond-10.jpg',
    externalURL: 'https://siambond.com/',
    featured: false,
    order: 4,
  },
  {
    title: 'Cario Golf Cart',
    slug: 'cario-golf-cart',
    category: 'website',
    description: 'Website design and development for Thai Summit Group',
    image: '/assets/work-cario-golf-cart-11.jpg',
    externalURL: 'https://cariogolfcart.com/',
    featured: false,
    order: 5,
  },
  {
    title: 'CA Oil (Mobil)',
    slug: 'ca-oil-mobil',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-ca-oil-12.jpg',
    externalURL: 'https://caoil.co.th/',
    featured: false,
    order: 6,
  },
  {
    title: 'ITALTHAI Engineering',
    slug: 'italthai-engineering',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-italthai-engineering-13.jpg',
    externalURL: 'https://italthaiengineering.com/',
    featured: false,
    order: 7,
  },
  {
    title: 'The Standard',
    slug: 'the-standard',
    category: 'website',
    description: 'WordPress website system development',
    image: '/assets/work-the-standard-14.jpg',
    externalURL: 'https://thestandard.co/',
    featured: false,
    order: 8,
  },
  {
    title: "It's Skin Thailand",
    slug: 'its-skin-thailand',
    category: 'ecommerce',
    description: 'E-commerce website design and development',
    image: '/assets/work-itsskin-15.jpg',
    featured: false,
    order: 9,
  },
  {
    title: 'Haus of Mana',
    slug: 'haus-of-mana',
    category: 'ecommerce',
    description: 'E-commerce website design and development',
    image: '/assets/work-haus-of-mana-16.jpg',
    externalURL: 'https://hausofmana.com/',
    featured: false,
    order: 10,
  },
  {
    title: 'IJ Siam',
    slug: 'ij-siam',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-ij-siam-17.jpg',
    externalURL: 'https://ijsiam.com/',
    featured: false,
    order: 11,
  },
  {
    title: 'Teeraporn Clinic',
    slug: 'teeraporn-clinic',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-teeraporn-18.jpg',
    externalURL: 'https://teerapornclinic.com/',
    featured: false,
    order: 12,
  },
  {
    title: 'The Olympic Committee of Thailand',
    slug: 'olympic-thai',
    category: 'website',
    description: 'Website design and development',
    image: '/assets/work-olympic-thai-19.jpg',
    externalURL: 'https://olympicthai.org/',
    featured: false,
    order: 13,
  },
  {
    title: 'Website Design Collection I',
    slug: 'website-design-collection-1',
    category: 'website',
    description: 'A collection of additional website design and development projects',
    image: '/assets/work-website-collection-20.jpg',
    featured: false,
    order: 14,
  },
  {
    title: 'Website Design Collection II',
    slug: 'website-design-collection-2',
    category: 'website',
    description: 'A collection of additional website design and development projects',
    image: '/assets/work-website-collection-21.jpg',
    featured: false,
    order: 15,
  },
  {
    title: 'Farm Design Thailand',
    slug: 'farm-design-thailand',
    category: 'crm',
    description: 'Sales promotion website development',
    image: '/assets/work-farm-design-23.jpg',
    featured: false,
    order: 16,
  },
  {
    title: 'CRM Platform Portfolio',
    slug: 'crm-platform-portfolio',
    category: 'crm',
    description: 'CRM platform campaigns developed for leading consumer brands',
    image: '/assets/work-crm-brand-portfolio-24.jpg',
    featured: false,
    order: 17,
  },
  {
    title: 'Logo & Corporate Identity Collection I',
    slug: 'logo-corporate-identity-collection-1',
    category: 'design',
    description: 'Logo and corporate identity design',
    image: '/assets/work-logo-ci-collection-26.jpg',
    featured: false,
    order: 18,
  },
  {
    title: 'Logo & Corporate Identity Collection II',
    slug: 'logo-corporate-identity-collection-2',
    category: 'design',
    description: 'Logo and corporate identity design',
    image: '/assets/work-logo-ci-collection-27.jpg',
    featured: false,
    order: 19,
  },
  {
    title: 'Logo & Corporate Identity Collection III',
    slug: 'logo-corporate-identity-collection-3',
    category: 'design',
    description: 'Logo and corporate identity design',
    image: '/assets/work-logo-ci-collection-28.jpg',
    featured: false,
    order: 20,
  },
  {
    title: 'Logo & Corporate Identity Collection IV',
    slug: 'logo-corporate-identity-collection-4',
    category: 'design',
    description: 'Logo and corporate identity design',
    image: '/assets/work-logo-ci-collection-29.jpg',
    featured: false,
    order: 21,
  },
  {
    title: 'Logo & Corporate Identity Collection V',
    slug: 'logo-corporate-identity-collection-5',
    category: 'design',
    description: 'Logo and corporate identity design',
    image: '/assets/work-logo-ci-collection-30.jpg',
    featured: false,
    order: 22,
  },
]
